version: '2.3'

services:
  postgres:
    container_name: diaspora_postgres
    image: postgres:13-alpine3.14
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=diaspora
      - POSTGRES_PASSWORD=diaspora
      - POSTGRES_DB=diaspora_production

  redis:
    container_name: diaspora_redis
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./redis:/data

  unicorn:
    container_name: diaspora_unicorn
    image: dsterry/diaspora
    restart: always
    command: bin/bundle exec unicorn -c config/unicorn.rb -E production
    volumes:
      - ./data:/diaspora/public/
      - ./tmp:/diaspora/tmp/
      - ./config/diaspora.toml:/diaspora/config/diaspora.toml
      - ./config/database.yml:/diaspora/config/database.yml
    depends_on:
      - postgres
      - redis
    ports:
      - 0.0.0.0:3000:3000

  sidekiq:
    container_name: diaspora_sidekiq
    image: dsterry/diaspora
    restart: always
    command: bin/bundle exec sidekiq
    volumes:
      - ./data:/diaspora/public/
      - ./config/diaspora.toml:/diaspora/config/diaspora.toml
      - ./config/database.yml:/diaspora/config/database.yml
    depends_on:
      - postgres
      - redis
